// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzIFzsOj1jN3mt49-aSCY7X9kK7wYwOQI',
    appId: '1:555115344003:web:34e9346279fb7cf8d72bb6',
    messagingSenderId: '555115344003',
    projectId: 'flutter-making-friend-app',
    authDomain: 'flutter-making-friend-app.firebaseapp.com',
    storageBucket: 'flutter-making-friend-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0v4_U5F__sgcJt8OBeYlY_l2ZZG4xhME',
    appId: '1:555115344003:android:60fa831c8c705a5cd72bb6',
    messagingSenderId: '555115344003',
    projectId: 'flutter-making-friend-app',
    storageBucket: 'flutter-making-friend-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyvqUSFb8ertvLCc8Hy0kgDs2Hr4XHqA',
    appId: '1:555115344003:ios:3c324e511f0bb8f2d72bb6',
    messagingSenderId: '555115344003',
    projectId: 'flutter-making-friend-app',
    storageBucket: 'flutter-making-friend-app.appspot.com',
    iosClientId: '555115344003-qh45b51v4dgt7nsqms1pfclm8d4ul6ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMakingFriendsApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyvqUSFb8ertvLCc8Hy0kgDs2Hr4XHqA',
    appId: '1:555115344003:ios:3c324e511f0bb8f2d72bb6',
    messagingSenderId: '555115344003',
    projectId: 'flutter-making-friend-app',
    storageBucket: 'flutter-making-friend-app.appspot.com',
    iosClientId: '555115344003-qh45b51v4dgt7nsqms1pfclm8d4ul6ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMakingFriendsApp2',
  );
}
